language: java
sudo: false
jdk:
- oraclejdk9
- oraclejdk8
- openjdk8
after_success:
- chmod -R 777 ./travis/after_success.sh
- "./travis/after_success.sh"
env:
  global:
  - secure: rsQxtOKQmfXYUeKwCfYUYwNFz6HqkGvQg/HNjOCz6DTBssOs9IupzGDCqrN2T+ltJ4VpJAR+ZuZKgo2h6u3l4M1SJQCrTninZYQdUo/lO8lBpz5jYV3AXA26OYKennkmP/uCUhhVKQ/NtrrM13HVV5a5SZaiJGBoRWQX37GCQqw=
  - secure: cL3tZO/NbGO9f8XhwCCvkCuJVD0LrxmOhusRhL14mjXrUuWCCOTSEhLrn0SDFyA6slFWuZEbJwSUXXra6Ym3Q+OYAtnjiuy4QMSZg85OAjGM5ib5X8P9Cz+XNBmyBeK/NJJRSnDiOafZx08A4OBrnTxvmkWKE7/LA00rUgP+Wt4=
  - secure: JpxebQkJogMK+Aft22NQWoW0xezWQRtHtoy9YckYNRSdFvF9uxL/wh7pl3U8jc9SeXvGpvJ0JXwPZXtLgkBzjTu4O50hpfrebzXmWRADNaH6QiTPvL0pch5DLzz7LQdj8mAdFcDHQWRzg6b3gMGfalvSW7uLQ0qnP75IEFFKfe4=
  - secure: NQRx/et3+4Q1JYowXbx/iyIqL7ma2qkwzvotBVl/6s735+RZ3hSylr95vsSym8kOPKjcwZHhGvOQbsnopyXoBp6rCj58atjmWcut5x9/LHFXl1aLygmh7NeJ+OXiQDXMjUzkrlYhkm6+zn/1QM0r/2phZb0MLGFoE+7iXHf0joU=
